language: java
before_install:
  # download the latest android sdk and unzip
  - wget http://dl.google.com/android/android-sdk_r18-linux.tgz
  - tar -zxf android-sdk_r18-linux.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  # only update the sdk for the tools and platform-tools (1,2) and whatever api level
  # you are building for android (run "android list sdk" to get the full list.  9 = 2.3.3 or API level 10
  - android update sdk --filter 1,2,9 --no-ui --force
#language: java
#jdk:
#- openjdk7
#- oraclejdk7
#- oraclejdk8
env:
  global:
  - secure: U4T6MOzC8a2hz36I7rAVOIUmoQbJ7c9sHF8W3Epf9tMLUcstG7RN3Kr2LAuGsSD9Nlgr0AY60SMSqOHNXedyT43n3fW0LVDF2+/HMl5ZWWCiTreaq11PgYKEuLHmAq5RAagiLiPFfT5JOiSs5FnOTM0n6795jkwM4UvU1Ob7DKU=
  - secure: OxWIPXLv+52nEBL4+sYyba8kPpihu2EPvitZ54g4SrJV0o29VDhFegJdx9FAAXAfh8NGJ1YozkMm2P+J2crylZYplHrF4Dvi7Gf9DDGLAKlc5Mf3Xb+toWwrYXFnoEr6LGGqwCCo1TJ15wfMUrRaUJucWkDi4ZhFt/TN/MAry74=
#addons:
 # sauce_connect: true